-- This table tells us what the launch date was for the use of
-- this application, by invoicing frequency. 
--
-- The launch date should be the first day of the invoice period
-- for a contractor's first invoice generated by this application.
-- We use this date to ensure that when we look back at sessions
-- that were paid before the invoice period, but not yet invoiced
-- (e.g. due to note status), that we don't go back too far and
-- potentially include every session the contractor has participated
-- in.
--
-- Launch date CANNOT be derived by looking at invoice details, because
-- this value is required even BEFORE the first set of invoice details
-- are captured in the table.
--
-- If there are sessions that a contractor hasn't invoiced for yet,
-- that were paid before the contractor's launch date, they can be
-- identified in the non_invoiced_session table, which will guarantee
-- their inclusion on an invoice once they're eligible (e.g. once the
-- note has been completed)
--
-- A contractor who invoices monthly, will have a different
-- launch date than a contractor who invoices bi-weekly, because
-- a bi-weekly invoice may not start on the first of a month. That
-- is why we have different launch dates for different contractors.

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[app_launch] (
    [invoice_frequency] NVARCHAR(50) NOT NULL,
    [launch_date]   DATE NOT NULL,
    CONSTRAINT [PK_app_launch] PRIMARY KEY CLUSTERED ([invoice_frequency] ASC)
);
